### PR TITLE
Comp 120 Audio (Not Complete)

### PR DESCRIPTION
**Pull request by sw180283**
I was having some issues with sample size numbers, which are labelled in the section. Parsing is still left to do and improvements to be made on echoes.

### CODE REVIEW

**Comment by sw180283** [comment]
Audio2 is the most recent file version

**Comment by Adrir** [comment]
The bak and log files do not need to be checked into GitHub. These can be added to .gitignore and deleted from the repository.

**Comment by Adrir** [comment]
I suggest consolidating the code into a single python file.

**Comment by Adrir** [comment]
There is no need to add files such as 'old' and 'newest'. All check-ins are dated. Further to this, Git _is_ a version control system. You can look back at any commit and [revert to it](https://help.github.com/desktop/guides/contributing/reverting-a-commit/) if absolutely necessary.

**Pull request closed without merging**
